project_id = "dajowxmdmnsvckdkugmd"

[functions.generate-openai-health-insights]
verify_jwt = false

[functions.generate-ai-risk-scores]
verify_jwt = false

[functions.generate-biomarker-recommendations]
verify_jwt = false

[functions.generate-analysis-recommendations]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false