// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvxulelfmkbyeoxhtfpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2eHVsZWxmbWtieWVveGh0ZnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDQ3MDAsImV4cCI6MjA2MjEyMDcwMH0.BLd4Z9X3l8zxSPFOt4PVNpHXgrbDcsa2SBm1zyoGXP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);